/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_MESSAGE_PB_H_INCLUDED
#define PB_MESSAGE_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _DataType {
    DataType_UNKNOWN = 0,
    DataType_UINT8 = 1,
    DataType_INT8 = 2,
    DataType_UINT16 = 3,
    DataType_INT16 = 4,
    DataType_UINT32 = 5,
    DataType_INT32 = 6,
    DataType_UINT64 = 7,
    DataType_INT64 = 8,
    DataType_FLOAT = 9,
    DataType_DOUBLE = 10,
    DataType_BOOL = 11,
    DataType_STRING = 12
} DataType;

typedef enum _StatusCode {
    StatusCode_OK = 0,
    StatusCode_FAILED = 1
} StatusCode;

typedef enum _ParameterType {
    ParameterType_INPUT = 0,
    ParameterType_OUTPUT = 1,
    ParameterType_PARAMETER_FIXED = 2,
    ParameterType_PARAMETER_PARAMETER = 3,
    ParameterType_PARAMETER_PERSISTENT = 4
} ParameterType;

/* Struct definitions */
typedef struct _Header {
    uint32_t frame_counter;
    uint64_t timestamp;
} Header;

typedef PB_BYTES_ARRAY_T(1024) GetParameterFromPathMsg_value_t;
typedef struct _GetParameterFromPathMsg {
    bool has_header;
    Header header;
    char param_key[1025];
    GetParameterFromPathMsg_value_t value;
} GetParameterFromPathMsg;

typedef PB_BYTES_ARRAY_T(1024) GetParameterMsg_value_t;
typedef struct _GetParameterMsg {
    bool has_header;
    Header header;
    uint32_t index;
    GetParameterMsg_value_t value;
} GetParameterMsg;

typedef struct _GetParameterInfoMsg {
    bool has_header;
    Header header;
    char param_key[1025];
} GetParameterInfoMsg;

typedef PB_BYTES_ARRAY_T(1024) ParameterInfoMsg_value_t;
typedef struct _ParameterInfoMsg {
    bool has_header;
    Header header;
    char param_key[1025];
    uint32_t index;
    DataType datatype;
    uint32_t nele;
    uint32_t size;
    ParameterInfoMsg_value_t value;
    uint32_t paramtype;
    bool link_active;
} ParameterInfoMsg;

typedef PB_BYTES_ARRAY_T(1024) SetParameterMsg_value_t;
typedef struct _SetParameterMsg {
    bool has_header;
    Header header;
    uint32_t index;
    uint32_t offset;
    uint32_t length;
    SetParameterMsg_value_t value;
} SetParameterMsg;

typedef struct _SaveMsg {
    bool has_header;
    Header header;
    char path[1025];
    char filename[65];
} SaveMsg;

typedef struct _GetLinkInfoMsg {
    bool has_header;
    Header header;
    char param_key[1025];
} GetLinkInfoMsg;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _DataType_MIN DataType_UNKNOWN
#define _DataType_MAX DataType_STRING
#define _DataType_ARRAYSIZE ((DataType)(DataType_STRING+1))

#define _StatusCode_MIN StatusCode_OK
#define _StatusCode_MAX StatusCode_FAILED
#define _StatusCode_ARRAYSIZE ((StatusCode)(StatusCode_FAILED+1))

#define _ParameterType_MIN ParameterType_INPUT
#define _ParameterType_MAX ParameterType_PARAMETER_PERSISTENT
#define _ParameterType_ARRAYSIZE ((ParameterType)(ParameterType_PARAMETER_PERSISTENT+1))





#define ParameterInfoMsg_datatype_ENUMTYPE DataType





/* Initializer values for message structs */
#define Header_init_default                      {0, 0}
#define GetParameterFromPathMsg_init_default     {false, Header_init_default, "", {0, {0}}}
#define GetParameterMsg_init_default             {false, Header_init_default, 0, {0, {0}}}
#define GetParameterInfoMsg_init_default         {false, Header_init_default, ""}
#define ParameterInfoMsg_init_default            {false, Header_init_default, "", 0, _DataType_MIN, 0, 0, {0, {0}}, 0, 0}
#define SetParameterMsg_init_default             {false, Header_init_default, 0, 0, 0, {0, {0}}}
#define SaveMsg_init_default                     {false, Header_init_default, "", ""}
#define GetLinkInfoMsg_init_default              {false, Header_init_default, ""}
#define Header_init_zero                         {0, 0}
#define GetParameterFromPathMsg_init_zero        {false, Header_init_zero, "", {0, {0}}}
#define GetParameterMsg_init_zero                {false, Header_init_zero, 0, {0, {0}}}
#define GetParameterInfoMsg_init_zero            {false, Header_init_zero, ""}
#define ParameterInfoMsg_init_zero               {false, Header_init_zero, "", 0, _DataType_MIN, 0, 0, {0, {0}}, 0, 0}
#define SetParameterMsg_init_zero                {false, Header_init_zero, 0, 0, 0, {0, {0}}}
#define SaveMsg_init_zero                        {false, Header_init_zero, "", ""}
#define GetLinkInfoMsg_init_zero                 {false, Header_init_zero, ""}

/* Field tags (for use in manual encoding/decoding) */
#define Header_frame_counter_tag                 1
#define Header_timestamp_tag                     2
#define GetParameterFromPathMsg_header_tag       1
#define GetParameterFromPathMsg_param_key_tag    2
#define GetParameterFromPathMsg_value_tag        3
#define GetParameterMsg_header_tag               1
#define GetParameterMsg_index_tag                2
#define GetParameterMsg_value_tag                3
#define GetParameterInfoMsg_header_tag           1
#define GetParameterInfoMsg_param_key_tag        2
#define ParameterInfoMsg_header_tag              1
#define ParameterInfoMsg_param_key_tag           2
#define ParameterInfoMsg_index_tag               3
#define ParameterInfoMsg_datatype_tag            4
#define ParameterInfoMsg_nele_tag                5
#define ParameterInfoMsg_size_tag                6
#define ParameterInfoMsg_value_tag               7
#define ParameterInfoMsg_paramtype_tag           8
#define ParameterInfoMsg_link_active_tag         9
#define SetParameterMsg_header_tag               1
#define SetParameterMsg_index_tag                2
#define SetParameterMsg_offset_tag               3
#define SetParameterMsg_length_tag               4
#define SetParameterMsg_value_tag                5
#define SaveMsg_header_tag                       1
#define SaveMsg_path_tag                         2
#define SaveMsg_filename_tag                     3
#define GetLinkInfoMsg_header_tag                1
#define GetLinkInfoMsg_param_key_tag             2

/* Struct field encoding specification for nanopb */
#define Header_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   frame_counter,     1) \
X(a, STATIC,   SINGULAR, UINT64,   timestamp,         2)
#define Header_CALLBACK NULL
#define Header_DEFAULT NULL

#define GetParameterFromPathMsg_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  header,            1) \
X(a, STATIC,   SINGULAR, STRING,   param_key,         2) \
X(a, STATIC,   SINGULAR, BYTES,    value,             3)
#define GetParameterFromPathMsg_CALLBACK NULL
#define GetParameterFromPathMsg_DEFAULT NULL
#define GetParameterFromPathMsg_header_MSGTYPE Header

#define GetParameterMsg_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  header,            1) \
X(a, STATIC,   SINGULAR, UINT32,   index,             2) \
X(a, STATIC,   SINGULAR, BYTES,    value,             3)
#define GetParameterMsg_CALLBACK NULL
#define GetParameterMsg_DEFAULT NULL
#define GetParameterMsg_header_MSGTYPE Header

#define GetParameterInfoMsg_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  header,            1) \
X(a, STATIC,   SINGULAR, STRING,   param_key,         2)
#define GetParameterInfoMsg_CALLBACK NULL
#define GetParameterInfoMsg_DEFAULT NULL
#define GetParameterInfoMsg_header_MSGTYPE Header

#define ParameterInfoMsg_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  header,            1) \
X(a, STATIC,   SINGULAR, STRING,   param_key,         2) \
X(a, STATIC,   SINGULAR, UINT32,   index,             3) \
X(a, STATIC,   SINGULAR, UENUM,    datatype,          4) \
X(a, STATIC,   SINGULAR, UINT32,   nele,              5) \
X(a, STATIC,   SINGULAR, UINT32,   size,              6) \
X(a, STATIC,   SINGULAR, BYTES,    value,             7) \
X(a, STATIC,   SINGULAR, UINT32,   paramtype,         8) \
X(a, STATIC,   SINGULAR, BOOL,     link_active,       9)
#define ParameterInfoMsg_CALLBACK NULL
#define ParameterInfoMsg_DEFAULT NULL
#define ParameterInfoMsg_header_MSGTYPE Header

#define SetParameterMsg_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  header,            1) \
X(a, STATIC,   SINGULAR, UINT32,   index,             2) \
X(a, STATIC,   SINGULAR, UINT32,   offset,            3) \
X(a, STATIC,   SINGULAR, UINT32,   length,            4) \
X(a, STATIC,   SINGULAR, BYTES,    value,             5)
#define SetParameterMsg_CALLBACK NULL
#define SetParameterMsg_DEFAULT NULL
#define SetParameterMsg_header_MSGTYPE Header

#define SaveMsg_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  header,            1) \
X(a, STATIC,   SINGULAR, STRING,   path,              2) \
X(a, STATIC,   SINGULAR, STRING,   filename,          3)
#define SaveMsg_CALLBACK NULL
#define SaveMsg_DEFAULT NULL
#define SaveMsg_header_MSGTYPE Header

#define GetLinkInfoMsg_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  header,            1) \
X(a, STATIC,   SINGULAR, STRING,   param_key,         2)
#define GetLinkInfoMsg_CALLBACK NULL
#define GetLinkInfoMsg_DEFAULT NULL
#define GetLinkInfoMsg_header_MSGTYPE Header

extern const pb_msgdesc_t Header_msg;
extern const pb_msgdesc_t GetParameterFromPathMsg_msg;
extern const pb_msgdesc_t GetParameterMsg_msg;
extern const pb_msgdesc_t GetParameterInfoMsg_msg;
extern const pb_msgdesc_t ParameterInfoMsg_msg;
extern const pb_msgdesc_t SetParameterMsg_msg;
extern const pb_msgdesc_t SaveMsg_msg;
extern const pb_msgdesc_t GetLinkInfoMsg_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define Header_fields &Header_msg
#define GetParameterFromPathMsg_fields &GetParameterFromPathMsg_msg
#define GetParameterMsg_fields &GetParameterMsg_msg
#define GetParameterInfoMsg_fields &GetParameterInfoMsg_msg
#define ParameterInfoMsg_fields &ParameterInfoMsg_msg
#define SetParameterMsg_fields &SetParameterMsg_msg
#define SaveMsg_fields &SaveMsg_msg
#define GetLinkInfoMsg_fields &GetLinkInfoMsg_msg

/* Maximum encoded size of messages (where known) */
#define GetLinkInfoMsg_size                      1046
#define GetParameterFromPathMsg_size             2073
#define GetParameterInfoMsg_size                 1046
#define GetParameterMsg_size                     1052
#define Header_size                              17
#define MESSAGE_PB_H_MAX_SIZE                    ParameterInfoMsg_size
#define ParameterInfoMsg_size                    2101
#define SaveMsg_size                             1112
#define SetParameterMsg_size                     1064

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
