/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "message.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(Header, Header, AUTO)


PB_BIND(GetParameterFromPathMsg, GetParameterFromPathMsg, 2)


PB_BIND(GetParameterMsg, GetParameterMsg, 2)


PB_BIND(GetParameterInfoMsg, GetParameterInfoMsg, 2)


PB_BIND(ParameterInfoMsg, ParameterInfoMsg, 2)


PB_BIND(SetParameterMsg, SetParameterMsg, 2)


PB_BIND(SaveMsg, SaveMsg, 2)


PB_BIND(GetLinkInfoMsg, GetLinkInfoMsg, 2)









